const fs=require('fs');const vm=require('vm');const assert=require('assert');
const code=fs.readFileSync('bookings-v2.js','utf8');
const storage={};const document={head:{appendChild(){}},createElement(){return {id:'',textContent:''}},getElementById(){return null}};
const context={console,document,window:{scrollTo(){}},globalThis:null,state:{},STORE:'dwajp-trip-v5',localStorage:{setItem(k,v){storage[k]=v}},esc:x=>String(x??''),backBar:()=>'<div>back</div>',renderHome(){},isLocked:()=>false,alert(){},confirm:()=>true};context.globalThis=context;vm.createContext(context);vm.runInContext(code,context);
const api=context.DWAJP_BOOKINGS;
assert.ok(api,'test API is exposed');
assert.ok(api.categories.includes('Flight'));assert.ok(api.categories.includes('RV Park / Campground'));assert.ok(api.categories.includes('Car / RV Hire'));
assert.equal(api.bookingLocksDate({category:'Accommodation',status:'CONFIRMED',startDate:'2026-09-22',endDate:'2026-09-24'},'2026-09-22'),true);
assert.equal(api.bookingLocksDate({category:'Accommodation',status:'CONFIRMED',startDate:'2026-09-22',endDate:'2026-09-24'},'2026-09-23'),true);
assert.equal(api.bookingLocksDate({category:'Accommodation',status:'CONFIRMED',startDate:'2026-09-22',endDate:'2026-09-24'},'2026-09-24'),false,'checkout date is not treated as an occupied accommodation night');
assert.equal(api.bookingLocksDate({category:'Flight',status:'CONFIRMED',startDate:'2026-10-27',endDate:'2026-10-27'},'2026-10-27'),true);
assert.equal(api.bookingLocksDate({category:'Flight',status:'UNCONFIRMED',startDate:'2026-10-27',endDate:'2026-10-27'},'2026-10-27'),false);
assert.equal(api.bookingLocksDate({category:'Car / RV Hire',status:'CONFIRMED',startDate:'2026-09-04',endDate:'2026-10-20'},'2026-09-04'),true,'vehicle pickup locks pickup day');
assert.equal(api.bookingLocksDate({category:'Car / RV Hire',status:'CONFIRMED',startDate:'2026-09-04',endDate:'2026-10-20'},'2026-10-20'),true,'vehicle return locks return day');
assert.equal(api.bookingLocksDate({category:'Car / RV Hire',status:'CONFIRMED',startDate:'2026-09-04',endDate:'2026-10-20'},'2026-09-10'),false,'vehicle hire does not lock every day in between');
const parsed=api.parseBookingText('French Quarter RV Resort\n22 Sep 2026 to 24 Sep 2026\nConfirmation 2026075827\n+1 504-586-3000');
assert.equal(parsed.category,'RV Park / Campground');assert.equal(parsed.startDate,'2026-09-22');assert.equal(parsed.endDate,'2026-09-24');assert.equal(parsed.confirmation,'2026075827');
const flight=api.parseBookingText('Qantas Flight QF94\n27 Oct 2026\nBooking reference D4I8WC');assert.equal(flight.category,'Flight');assert.equal(flight.startDate,'2026-10-27');assert.equal(flight.confirmation,'D4I8WC');
assert.equal(context.isLocked({date:'2026-09-22'}),true,'seeded confirmed RV park locks check-in night');
assert.equal(context.isLocked({date:'2026-10-27'}),true,'seeded confirmed flight locks departure day');
assert.equal(context.isLocked({date:'2026-09-10'}),false,'ordinary day remains flexible');
assert.match(code,/ADD BOOKING/);assert.match(code,/QUICK PRINT/);assert.match(code,/CONFIRMED — LOCK DATES/);assert.match(code,/@media\(max-width:720px\)/,'phone layout exists');assert.match(code,/booking-form-grid/,'booking form responsive grid exists');assert.match(code,/dictateBooking/,'dictation helper exists');assert.match(code,/autoFillBooking/,'paste auto-fill helper exists');
console.log('bookings-v2 tests passed');
