// PR #3 CI trigger: Find & Fill search normalization
const fs=require('fs');const vm=require('vm');const assert=require('assert');
const code=fs.readFileSync('bookings-v2.js','utf8');
const storage={};const document={head:{appendChild(){}},createElement(){return {id:'',textContent:'',innerHTML:'',firstElementChild:null}},getElementById(){return null}};
const context={console,URL,document,window:{scrollTo(){}},globalThis:null,state:{},STORE:'dwajp-trip-v5',localStorage:{setItem(k,v){storage[k]=v}},esc:x=>String(x??''),backBar:()=>'<div>back</div>',renderHome(){},isLocked:()=>false,alert(){},confirm:()=>true};context.globalThis=context;vm.createContext(context);vm.runInContext(code,context);
const api=context.DWAJP_BOOKINGS;assert.ok(api,'test API is exposed');
assert.ok(api.categories.includes('Flight'));assert.ok(api.categories.includes('RV Park / Campground'));assert.ok(api.categories.includes('Car / RV Hire'));
assert.equal(api.bookingLocksDate({category:'Accommodation',status:'CONFIRMED',startDate:'2026-09-22',endDate:'2026-09-24'},'2026-09-22'),true);assert.equal(api.bookingLocksDate({category:'Accommodation',status:'CONFIRMED',startDate:'2026-09-22',endDate:'2026-09-24'},'2026-09-24'),false);
assert.equal(api.bookingLocksDate({category:'Car / RV Hire',status:'CONFIRMED',startDate:'2026-09-04',endDate:'2026-10-20'},'2026-09-10'),false);
const parsed=api.parseBookingText('French Quarter RV Resort\n22 Sep 2026 to 24 Sep 2026\nConfirmation 2026075827\n+1 504-586-3000');assert.equal(parsed.category,'RV Park / Campground');assert.equal(parsed.startDate,'2026-09-22');assert.equal(parsed.endDate,'2026-09-24');assert.equal(parsed.confirmation,'2026075827');
const flight=api.parseBookingText('Qantas Flight QF94\n27 Oct 2026\nBooking reference D4I8WC');assert.equal(flight.category,'Flight');assert.equal(flight.startDate,'2026-10-27');assert.equal(flight.confirmation,'D4I8WC');
const gallivant=api.parseBookingText('the galavant NYC 1 september to the 4 september');assert.equal(gallivant.category,'Accommodation','plain-language hotel input is recognised');assert.equal(gallivant.startDate,'2026-09-01','start of conversational date range');assert.equal(gallivant.endDate,'2026-09-04','end of conversational date range');assert.match(gallivant.title,/Gallivant New York City/i,'user typo and NYC are normalized before place search');assert.equal(gallivant.notes,'','simple request is not dumped into notes');
assert.equal(context.isLocked({date:'2026-09-22'}),true);assert.equal(context.isLocked({date:'2026-10-27'}),true);assert.equal(context.isLocked({date:'2026-09-10'}),false);
assert.match(code,/FIND & FILL DETAILS/);assert.match(code,/OPEN WEBSITE/,'booking form offers one-tap website button');assert.match(code,/CONFIRMED • LOCKED/,'day cards visibly label confirmed bookings');assert.match(code,/day-booking-confirmed/,'confirmed day booking styling exists');assert.match(code,/confirmedAccommodationForDay/,'confirmed accommodation is detected per day');assert.match(code,/confirmedBookingsForDate\(day.date\)/,'day accommodation uses protected-night matching rather than checkout-inclusive touching dates');assert.match(code,/confirmedBookingPlanCell/,'confirmed booking replaces the plan slot');assert.match(code,/bookingContactCell/,'confirmed booking details replace the day contact section');assert.match(code,/querySelector\('\.overnight-suggestions'\)\?\.remove/,'confirmed stay removes overnight suggestions');assert.match(code,/openBookingWebsite/);assert.match(code,/refreshBookingWebsiteButton/);assert.match(code,/bookingWebsite/);assert.match(code,/Website/);assert.match(code,/searchPlace/);assert.match(code,/namedetails=1/);assert.match(code,/extratags=1/);assert.match(code,/@media\(max-width:720px\)/);assert.match(code,/dictateBooking/);assert.match(code,/galavant\\b\/gi,'Gallivant'/,'search normalises common Gallivant misspelling');assert.match(code,/New York City/,'NYC is expanded for place search');assert.match(code,/The Gallivant Times Square/,'Gallivant fallback search exists');
console.log('bookings-v2 Find & Fill tests passed');
